In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('hotel_bookings.csv')

In [4]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [6]:
df=pd.read_csv('hotel_bookings.csv',index_col=0)

In [7]:
df.head()

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
hotel,,,,,,,,,,,,,,,,,,,,,
Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 119390 entries, Resort Hotel to City Hotel
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   is_canceled                     119390 non-null  int64
 1   lead_time                       119390 non-null  int64
 2   arrival_date_year               119390 non-null  int64
 3   arrival_date_month              119390 non-null  object
 4   arrival_date_week_number        119390 non-null  int64
 5   arrival_date_day_of_month       119390 non-null  int64
 6   stays_in_weekend_nights         119390 non-null  int64
 7   stays_in_week_nights            119390 non-null  int64
 8   adults                          119390 non-null  int64
 9   children                        119386 non-null  float64
 10  babies                          119390 non-null  int64
 11  meal                            119390 non-null  object
 12  country                         118902 non-null  object
 13  market_segment                  119390 non-null  object
 14  distribution_channel            119390 non-null  object
 15  is_repeated_guest               119390 non-null  int64
 16  previous_cancellations          119390 non-null  int64
 17  previous_bookings_not_canceled  119390 non-null  int64
 18  reserved_room_type              119390 non-null  object
 19  assigned_room_type              119390 non-null  object
 20  booking_changes                 119390 non-null  int64
 21  deposit_type                    119390 non-null  object
 22  agent                           103050 non-null  float64
 23  company                         6797 non-null    float64
 24  days_in_waiting_list            119390 non-null  int64
 25  customer_type                   119390 non-null  object
 26  adr                             119390 non-null  float64
 27  required_car_parking_spaces     119390 non-null  int64
 28  total_of_special_requests       119390 non-null  int64
 29  reservation_status              119390 non-null  object
 30  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(11)
memory usage: 29.1+ MB

In [9]:
df=df.drop_duplicates()

In [10]:
df.isnull().sum()

is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              4
babies                                0
meal                                  0
country                             452
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             12193
company                           82137
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

In [11]:
children=df['children']

In [12]:
children.head()

hotel
Resort Hotel    0.0
Resort Hotel    0.0
Resort Hotel    0.0
Resort Hotel    0.0
Resort Hotel    0.0
Name: children, dtype: float64

In [13]:
c_mean=children.mean()

In [14]:
c_mean

0.13863969242035884

In [15]:
children.fillna(int(c_mean),inplace=True)

In [16]:
df.isnull().sum()

is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              0
babies                                0
meal                                  0
country                             452
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             12193
company                           82137
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

In [17]:
df.dropna()

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
hotel,,,,,,,,,,,,,,,,,,,,,
Resort Hotel,0,6,2015,October,42,11,2,0,2,0.0,...,No Deposit,240.0,113.0,0,Transient,82.0,1,1,Check-Out,2015-10-13
Resort Hotel,0,24,2015,October,44,26,7,15,1,0.0,...,No Deposit,185.0,281.0,0,Transient-Party,52.2,0,0,Check-Out,2015-11-17
Resort Hotel,0,24,2015,November,45,3,0,3,2,0.0,...,No Deposit,334.0,281.0,0,Transient-Party,48.0,0,0,Check-Out,2015-11-06
Resort Hotel,0,24,2015,November,45,3,2,10,1,0.0,...,No Deposit,328.0,281.0,0,Transient-Party,40.0,0,0,Check-Out,2015-11-15
Resort Hotel,0,24,2015,November,45,3,3,10,2,0.0,...,No Deposit,326.0,281.0,0,Transient-Party,48.0,0,0,Check-Out,2015-11-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
City Hotel,0,13,2017,May,21,24,0,1,2,0.0,...,No Deposit,9.0,478.0,0,Transient-Party,150.0,0,1,Check-Out,2017-05-25
City Hotel,0,13,2017,May,22,29,1,3,1,0.0,...,No Deposit,290.0,148.0,0,Transient,95.0,0,0,Check-Out,2017-06-02
City Hotel,0,13,2017,May,22,29,1,3,2,0.0,...,No Deposit,290.0,148.0,0,Transient,110.0,0,0,Check-Out,2017-06-02
City Hotel,0,210,2017,June,23,9,0,1,2,0.0,...,No Deposit,14.0,229.0,0,Transient,135.0,0,0,Check-Out,2017-06-10
City Hotel,0,191,2017,July,29,16,2,2,2,0.0,...,No Deposit,9.0,421.0,0,Transient,120.6,0,2,Check-Out,2017-07-20

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, Resort Hotel to City Hotel
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   is_canceled                     87396 non-null  int64
 1   lead_time                       87396 non-null  int64
 2   arrival_date_year               87396 non-null  int64
 3   arrival_date_month              87396 non-null  object
 4   arrival_date_week_number        87396 non-null  int64
 5   arrival_date_day_of_month       87396 non-null  int64
 6   stays_in_weekend_nights         87396 non-null  int64
 7   stays_in_week_nights            87396 non-null  int64
 8   adults                          87396 non-null  int64
 9   children                        87396 non-null  float64
 10  babies                          87396 non-null  int64
 11  meal                            87396 non-null  object
 12  country                         86944 non-null  object
 13  market_segment                  87396 non-null  object
 14  distribution_channel            87396 non-null  object
 15  is_repeated_guest               87396 non-null  int64
 16  previous_cancellations          87396 non-null  int64
 17  previous_bookings_not_canceled  87396 non-null  int64
 18  reserved_room_type              87396 non-null  object
 19  assigned_room_type              87396 non-null  object
 20  booking_changes                 87396 non-null  int64
 21  deposit_type                    87396 non-null  object
 22  agent                           75203 non-null  float64
 23  company                         5259 non-null   float64
 24  days_in_waiting_list            87396 non-null  int64
 25  customer_type                   87396 non-null  object
 26  adr                             87396 non-null  float64
 27  required_car_parking_spaces     87396 non-null  int64
 28  total_of_special_requests       87396 non-null  int64
 29  reservation_status              87396 non-null  object
 30  reservation_status_date         87396 non-null  object
dtypes: float64(4), int64(16), object(11)
memory usage: 23.8+ MB

In [19]:
df.isnull().sum()

is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              0
babies                                0
meal                                  0
country                             452
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             12193
company                           82137
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

In [20]:
df.dropna()

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
hotel,,,,,,,,,,,,,,,,,,,,,
Resort Hotel,0,6,2015,October,42,11,2,0,2,0.0,...,No Deposit,240.0,113.0,0,Transient,82.0,1,1,Check-Out,2015-10-13
Resort Hotel,0,24,2015,October,44,26,7,15,1,0.0,...,No Deposit,185.0,281.0,0,Transient-Party,52.2,0,0,Check-Out,2015-11-17
Resort Hotel,0,24,2015,November,45,3,0,3,2,0.0,...,No Deposit,334.0,281.0,0,Transient-Party,48.0,0,0,Check-Out,2015-11-06
Resort Hotel,0,24,2015,November,45,3,2,10,1,0.0,...,No Deposit,328.0,281.0,0,Transient-Party,40.0,0,0,Check-Out,2015-11-15
Resort Hotel,0,24,2015,November,45,3,3,10,2,0.0,...,No Deposit,326.0,281.0,0,Transient-Party,48.0,0,0,Check-Out,2015-11-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
City Hotel,0,13,2017,May,21,24,0,1,2,0.0,...,No Deposit,9.0,478.0,0,Transient-Party,150.0,0,1,Check-Out,2017-05-25
City Hotel,0,13,2017,May,22,29,1,3,1,0.0,...,No Deposit,290.0,148.0,0,Transient,95.0,0,0,Check-Out,2017-06-02
City Hotel,0,13,2017,May,22,29,1,3,2,0.0,...,No Deposit,290.0,148.0,0,Transient,110.0,0,0,Check-Out,2017-06-02
City Hotel,0,210,2017,June,23,9,0,1,2,0.0,...,No Deposit,14.0,229.0,0,Transient,135.0,0,0,Check-Out,2017-06-10
City Hotel,0,191,2017,July,29,16,2,2,2,0.0,...,No Deposit,9.0,421.0,0,Transient,120.6,0,2,Check-Out,2017-07-20

In [21]:
df.dropna(inplace=True)

In [22]:
df.isnull().sum()

is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64